/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         afterTokenRedirect: "after_token_redirect"
 *     }
 */
export interface ConnectorsOAuthAuthorizeRequest {
    /**
     * The URL to redirect to after the connector has been authorized.
     */
    afterTokenRedirect?: string;
}
