// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { BatchStatus } from "./BatchStatus";

export const Batch: core.serialization.ObjectSchema<serializers.Batch.Raw, Cohere.Batch> = core.serialization.object({
    id: core.serialization.string().optional(),
    name: core.serialization.string(),
    creatorId: core.serialization.property("creator_id", core.serialization.string().optional()),
    orgId: core.serialization.property("org_id", core.serialization.string().optional()),
    status: BatchStatus.optional(),
    createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date().optional()),
    inputDatasetId: core.serialization.property("input_dataset_id", core.serialization.string()),
    outputDatasetId: core.serialization.property("output_dataset_id", core.serialization.string().optional()),
    inputTokens: core.serialization.property("input_tokens", core.serialization.string().optional()),
    outputTokens: core.serialization.property("output_tokens", core.serialization.string().optional()),
    model: core.serialization.string(),
    numRecords: core.serialization.property("num_records", core.serialization.number().optional()),
    numSuccessfulRecords: core.serialization.property("num_successful_records", core.serialization.number().optional()),
    numFailedRecords: core.serialization.property("num_failed_records", core.serialization.number().optional()),
    statusReason: core.serialization.property("status_reason", core.serialization.string().optional()),
});

export declare namespace Batch {
    export interface Raw {
        id?: string | null;
        name: string;
        creator_id?: string | null;
        org_id?: string | null;
        status?: BatchStatus.Raw | null;
        created_at?: string | null;
        updated_at?: string | null;
        input_dataset_id: string;
        output_dataset_id?: string | null;
        input_tokens?: string | null;
        output_tokens?: string | null;
        model: string;
        num_records?: number | null;
        num_successful_records?: number | null;
        num_failed_records?: number | null;
        status_reason?: string | null;
    }
}
