/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cohere from "../../../../api/index";
import * as core from "../../../../core";
import { Batch } from "./Batch";

export const ListBatchesResponse: core.serialization.ObjectSchema<
    serializers.ListBatchesResponse.Raw,
    Cohere.ListBatchesResponse
> = core.serialization.object({
    batches: core.serialization.list(Batch).optional(),
    nextPageToken: core.serialization.property("next_page_token", core.serialization.string().optional()),
});

export declare namespace ListBatchesResponse {
    export interface Raw {
        batches?: Batch.Raw[] | null;
        next_page_token?: string | null;
    }
}
