/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cohere from "../../../../index.js";

/**
 * @example
 *     {
 *         model: "model",
 *         dataset_id: "dataset_id",
 *         input_type: "search_document"
 *     }
 */
export interface CreateEmbedJobRequest {
    /**
     * ID of the embedding model.
     *
     * Available models and corresponding embedding dimensions:
     *
     * - `embed-english-v3.0` : 1024
     * - `embed-multilingual-v3.0` : 1024
     * - `embed-english-light-v3.0` : 384
     * - `embed-multilingual-light-v3.0` : 384
     */
    model: string;
    /** ID of a [Dataset](https://docs.cohere.com/docs/datasets). The Dataset must be of type `embed-input` and must have a validation status `Validated` */
    dataset_id: string;
    input_type: Cohere.EmbedInputType;
    /** The name of the embed job. */
    name?: string;
    /**
     * Specifies the types of embeddings you want to get back. Not required and default is None, which returns the Embed Floats response type. Can be one or more of the following types.
     *
     * * `"float"`: Use this when you want to get back the default float embeddings. Valid for all models.
     * * `"int8"`: Use this when you want to get back signed int8 embeddings. Valid for v3 and newer model versions.
     * * `"uint8"`: Use this when you want to get back unsigned int8 embeddings. Valid for v3 and newer model versions.
     * * `"binary"`: Use this when you want to get back signed binary embeddings. Valid for v3 and newer model versions.
     * * `"ubinary"`: Use this when you want to get back unsigned binary embeddings. Valid for v3 and newer model versions.
     */
    embedding_types?: Cohere.EmbeddingType[];
    /**
     * One of `START|END` to specify how the API will handle inputs longer than the maximum token length.
     *
     * Passing `START` will discard the start of the input. `END` will discard the end of the input. In both cases, input is discarded until the remaining input is exactly the maximum input token length for the model.
     */
    truncate?: CreateEmbedJobRequest.Truncate;
}

export namespace CreateEmbedJobRequest {
    /**
     * One of `START|END` to specify how the API will handle inputs longer than the maximum token length.
     *
     * Passing `START` will discard the start of the input. `END` will discard the end of the input. In both cases, input is discarded until the remaining input is exactly the maximum input token length for the model.
     */
    export type Truncate = "START" | "END";
    export const Truncate = {
        Start: "START",
        End: "END",
    } as const;
}
