// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../core";
import * as errors from "../../errors/index";

export class InvalidTokenError extends errors.CohereError {
    constructor(body?: unknown, rawResponse?: core.RawResponse) {
        super({
            message: "InvalidTokenError",
            statusCode: 498,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, InvalidTokenError.prototype);
    }
}
