// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../core";
import * as errors from "../../errors/index";

export class NotImplementedError extends errors.CohereError {
    constructor(body?: unknown, rawResponse?: core.RawResponse) {
        super({
            message: "NotImplementedError",
            statusCode: 501,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, NotImplementedError.prototype);
    }
}
