/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors/index";

export class ServiceUnavailableError extends errors.CohereError {
    constructor(body?: unknown) {
        super({
            message: "ServiceUnavailableError",
            statusCode: 503,
            body: body,
        });
        Object.setPrototypeOf(this, ServiceUnavailableError.prototype);
    }
}
