/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Cohere from "../../../../../../api";
import * as core from "../../../../../../core";

export const CreateFinetunedModelResponse: core.serialization.ObjectSchema<
    serializers.finetuning.CreateFinetunedModelResponse.Raw,
    Cohere.finetuning.CreateFinetunedModelResponse
> = core.serialization.object({
    finetunedModel: core.serialization.property(
        "finetuned_model",
        core.serialization.lazyObject(async () => (await import("../../../../..")).finetuning.FinetunedModel).optional()
    ),
});

export declare namespace CreateFinetunedModelResponse {
    interface Raw {
        finetuned_model?: serializers.finetuning.FinetunedModel.Raw | null;
    }
}
