// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";

export const DeleteFinetunedModelResponse: core.serialization.Schema<
    serializers.finetuning.DeleteFinetunedModelResponse.Raw,
    Cohere.finetuning.DeleteFinetunedModelResponse
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace DeleteFinetunedModelResponse {
    export type Raw = Record<string, unknown>;
}
