// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";
import { BaseModel } from "./BaseModel";
import { Hyperparameters } from "./Hyperparameters";
import { WandbConfig } from "./WandbConfig";

export const Settings: core.serialization.ObjectSchema<
    serializers.finetuning.Settings.Raw,
    Cohere.finetuning.Settings
> = core.serialization.object({
    baseModel: core.serialization.property("base_model", BaseModel),
    datasetId: core.serialization.property("dataset_id", core.serialization.string()),
    hyperparameters: Hyperparameters.optional(),
    multiLabel: core.serialization.property("multi_label", core.serialization.boolean().optional()),
    wandb: WandbConfig.optional(),
});

export declare namespace Settings {
    export interface Raw {
        base_model: BaseModel.Raw;
        dataset_id: string;
        hyperparameters?: Hyperparameters.Raw | null;
        multi_label?: boolean | null;
        wandb?: WandbConfig.Raw | null;
    }
}
