// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../../../../index";

/**
 * Response to request to create a fine-tuned model.
 */
export interface CreateFinetunedModelResponse {
    /** Information about the fine-tuned model. */
    finetunedModel?: Cohere.finetuning.FinetunedModel;
}
