/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The evaluation metrics at a given step of the training of a fine-tuned model.
 */
export interface TrainingStepMetrics {
    /** Creation timestamp. */
    created_at?: string;
    /** Step number. */
    step_number?: number;
    /** Map of names and values for each evaluation metrics. */
    metrics?: Record<string, number>;
}
