/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../index";
import * as Cohere from "../../../api/index";
import * as core from "../../../core";
import { GenerateRequestTruncate } from "../../types/GenerateRequestTruncate";
import { GenerateRequestReturnLikelihoods } from "../../types/GenerateRequestReturnLikelihoods";

export const GenerateRequest: core.serialization.Schema<serializers.GenerateRequest.Raw, Cohere.GenerateRequest> =
    core.serialization.object({
        prompt: core.serialization.string(),
        model: core.serialization.string().optional(),
        numGenerations: core.serialization.property("num_generations", core.serialization.number().optional()),
        maxTokens: core.serialization.property("max_tokens", core.serialization.number().optional()),
        truncate: GenerateRequestTruncate.optional(),
        temperature: core.serialization.number().optional(),
        seed: core.serialization.number().optional(),
        preset: core.serialization.string().optional(),
        endSequences: core.serialization.property(
            "end_sequences",
            core.serialization.list(core.serialization.string()).optional(),
        ),
        stopSequences: core.serialization.property(
            "stop_sequences",
            core.serialization.list(core.serialization.string()).optional(),
        ),
        k: core.serialization.number().optional(),
        p: core.serialization.number().optional(),
        frequencyPenalty: core.serialization.property("frequency_penalty", core.serialization.number().optional()),
        presencePenalty: core.serialization.property("presence_penalty", core.serialization.number().optional()),
        returnLikelihoods: core.serialization.property(
            "return_likelihoods",
            GenerateRequestReturnLikelihoods.optional(),
        ),
        rawPrompting: core.serialization.property("raw_prompting", core.serialization.boolean().optional()),
    });

export declare namespace GenerateRequest {
    export interface Raw {
        prompt: string;
        model?: string | null;
        num_generations?: number | null;
        max_tokens?: number | null;
        truncate?: GenerateRequestTruncate.Raw | null;
        temperature?: number | null;
        seed?: number | null;
        preset?: string | null;
        end_sequences?: string[] | null;
        stop_sequences?: string[] | null;
        k?: number | null;
        p?: number | null;
        frequency_penalty?: number | null;
        presence_penalty?: number | null;
        return_likelihoods?: GenerateRequestReturnLikelihoods.Raw | null;
        raw_prompting?: boolean | null;
    }
}
