/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cohere from "..";

export interface ApiMeta {
    apiVersion?: Cohere.ApiMetaApiVersion;
    warnings?: string[];
}
