/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cohere from "../index.js";

export type AssistantMessageContentItem = Cohere.AssistantMessageContentItem.Text;

export namespace AssistantMessageContentItem {
    export interface Text extends Cohere.ChatTextContent {
        type: "text";
    }
}
