/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cohere from "../index.js";

/**
 * A message from the assistant role can contain text and tool call information.
 */
export interface AssistantMessageResponse {
    role: "assistant";
    tool_calls?: Cohere.ToolCallV2[];
    /** A chain-of-thought style reflection and plan that the model generates when working with Tools. */
    tool_plan?: string;
    content?: Cohere.AssistantMessageResponseContentItem[];
    citations?: Cohere.Citation[];
}
