/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The token_type specifies the way the token is passed in the Authorization header. Valid values are "bearer", "basic", and "noscheme".
 */
export type AuthTokenType = "bearer" | "basic" | "noscheme";

export const AuthTokenType = {
    Bearer: "bearer",
    Basic: "basic",
    Noscheme: "noscheme",
} as const;
