// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../index";

export interface ChatToolPlanDeltaEventDelta {
    message?: Cohere.ChatToolPlanDeltaEventDeltaMessage;
}
