/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cohere from "../index.js";

/**
 * A streamed event delta which signifies a tool call has started streaming.
 */
export interface ChatToolCallStartEvent extends Cohere.ChatStreamEventType {
    index?: number;
    delta?: ChatToolCallStartEvent.Delta;
}

export namespace ChatToolCallStartEvent {
    export interface Delta {
        message?: Delta.Message;
    }

    export namespace Delta {
        export interface Message {
            tool_calls?: Cohere.ToolCallV2;
        }
    }
}
