/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cohere from "../index.js";

export interface ChatSearchResult {
    search_query?: Cohere.ChatSearchQuery;
    /** The connector from which this result comes from. */
    connector: Cohere.ChatSearchResultConnector;
    /** Identifiers of documents found by this search query. */
    document_ids: string[];
    /** An error message if the search failed. */
    error_message?: string;
    /** Whether a chat request should continue or not if the request to this connector fails. */
    continue_on_failure?: boolean;
}
