/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ChatMessageEndEventDelta {
    /** An error message if an error occurred during the generation. */
    error?: string;
}
