/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cohere from "..";

export interface ChatRequestToolResultsItem {
    call: Cohere.ToolCall;
    outputs: Record<string, unknown>[];
}
