/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ChatDataMetrics {
    /** The sum of all turns of valid train examples. */
    numTrainTurns?: string;
    /** The sum of all turns of valid eval examples. */
    numEvalTurns?: string;
    /** The preamble of this dataset. */
    preamble?: string;
}
