// This file was auto-generated by Fern from our API Definition.

/**
 * Defaults to `"enabled"`.
 * Citations are enabled by default for models that support it, but can be turned off by setting `"type": "disabled"`.
 *
 * Compatible Deployments: Cohere Platform, Azure, AWS Sagemaker/Bedrock, Private Deployments
 */
export const ChatStreamRequestCitationQuality = {
    Enabled: "ENABLED",
    Disabled: "DISABLED",
    Fast: "FAST",
    Accurate: "ACCURATE",
    Off: "OFF",
} as const;
export type ChatStreamRequestCitationQuality =
    (typeof ChatStreamRequestCitationQuality)[keyof typeof ChatStreamRequestCitationQuality];
