// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../index";

/**
 * A Content block which contains information about the content type and the content itself.
 */
export type Content = Cohere.Content.Text | Cohere.Content.ImageUrl;

export namespace Content {
    export interface Text extends Cohere.ChatTextContent {
        type: "text";
    }

    export interface ImageUrl extends Cohere.ImageContent {
        type: "image_url";
    }
}
