/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cohere from "../index.js";

/**
 * Response from creating an embed job.
 */
export interface CreateEmbedJobResponse {
    job_id: string;
    meta?: Cohere.ApiMeta;
}
