/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cohere from "../index.js";

/**
 * Document content.
 */
export interface DocumentContent {
    document: Cohere.Document;
}
