/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The truncation option used
 */
export type EmbedJobTruncate = "START" | "END";

export const EmbedJobTruncate = {
    Start: "START",
    End: "END",
} as const;
