/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cohere from "../index.js";

export type EmbedResponse = Cohere.EmbedResponse.EmbeddingsFloats | Cohere.EmbedResponse.EmbeddingsByType;

export namespace EmbedResponse {
    export interface EmbeddingsFloats extends Cohere.EmbedFloatsResponse {
        response_type: "embeddings_floats";
    }

    export interface EmbeddingsByType extends Cohere.EmbedByTypeResponse {
        response_type: "embeddings_by_type";
    }
}
