/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EmbedRequestEmbeddingTypesItem = "float" | "int8" | "uint8" | "binary" | "ubinary";

export const EmbedRequestEmbeddingTypesItem = {
    Float: "float",
    Int8: "int8",
    Uint8: "uint8",
    Binary: "binary",
    Ubinary: "ubinary",
} as const;
