// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../index";

export type EmbedContent = Cohere.EmbedContent.ImageUrl | Cohere.EmbedContent.Text;

export namespace EmbedContent {
    export interface ImageUrl extends Cohere.EmbedImage {
        type: "image_url";
    }

    export interface Text extends Cohere.EmbedText {
        type: "text";
    }
}
