/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetClusterJobResponseStatus = "unknown" | "processing" | "failed" | "complete" | "queued";

export const GetClusterJobResponseStatus = {
    Unknown: "unknown",
    Processing: "processing",
    Failed: "failed",
    Complete: "complete",
    Queued: "queued",
} as const;
