/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cohere from "../index";

export type Message = Cohere.Message.Chatbot | Cohere.Message.System | Cohere.Message.User | Cohere.Message.Tool;

export namespace Message {
    export interface Chatbot extends Cohere.ChatMessage {
        role: "CHATBOT";
    }

    export interface System extends Cohere.ChatMessage {
        role: "SYSTEM";
    }

    export interface User extends Cohere.ChatMessage {
        role: "USER";
    }

    export interface Tool extends Cohere.ToolMessage {
        role: "TOOL";
    }
}
