// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../index";

/**
 * A content block on a parsed page.
 */
export type ParseBlock = Cohere.ParseBlock.Text | Cohere.ParseBlock.Image | Cohere.ParseBlock.Table;

export namespace ParseBlock {
    export interface Text extends Cohere.ParseTextContentBlock {
        type: "text";
    }

    export interface Image extends Cohere.ParseImageContentBlock {
        type: "image";
    }

    export interface Table extends Cohere.ParseTableContentBlock {
        type: "table";
    }
}
