// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../index";

/**
 * A table content block.
 */
export interface ParseTableContentBlock {
    table: Cohere.ParseTableBlock;
}
