// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../index";

/**
 * Markdown output payload for a parsed page.
 */
export interface ParseMarkdownPage {
    /**
     * Page content as markdown. Images are embedded as
     * `![<description>](<image_id>)`. Tables are inlined as HTML.
     */
    content: string;
    /** Image metadata referenced from `content`. */
    images?: Cohere.ParseImageBlock[];
}
