// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../index";

/**
 * Response from the v2 parse endpoint.
 */
export interface ParseResponse {
    /** Unique identifier for the parse response. */
    id: string;
    /** Parsed pages in document order. */
    pages: Cohere.ParsePage[];
    meta?: Cohere.ApiMeta;
    /**
     * The reason parsing finished. For Parse, this is only ever `COMPLETE` or
     * `MAX_TOKENS`; `MAX_TOKENS` indicates the output was truncated because it
     * exceeded the maximum output token limit.
     */
    finishReason?: Cohere.ChatFinishReason;
}
