// This file was auto-generated by Fern from our API Definition.

/**
 * A bounding box with coordinates in [0, 1] relative to the source page (model
 * coordinates are thousandths of page width/height).
 */
export interface ParseBoundingBoxNormalized {
    /** Normalized X coordinate of the top-left corner. */
    topLeftX: number;
    /** Normalized Y coordinate of the top-left corner. */
    topLeftY: number;
    /** Normalized X coordinate of the bottom-right corner. */
    bottomRightX: number;
    /** Normalized Y coordinate of the bottom-right corner. */
    bottomRightY: number;
}
