/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cohere from "../index";

/**
 * StreamedChatResponse is returned in streaming mode (specified with `stream=True` in the request).
 */
export type StreamedChatResponse =
    | Cohere.StreamedChatResponse.StreamStart
    | Cohere.StreamedChatResponse.SearchQueriesGeneration
    | Cohere.StreamedChatResponse.SearchResults
    | Cohere.StreamedChatResponse.TextGeneration
    | Cohere.StreamedChatResponse.CitationGeneration
    | Cohere.StreamedChatResponse.ToolCallsGeneration
    | Cohere.StreamedChatResponse.StreamEnd
    | Cohere.StreamedChatResponse.ToolCallsChunk
    | Cohere.StreamedChatResponse.Debug;

export namespace StreamedChatResponse {
    export interface StreamStart extends Cohere.ChatStreamStartEvent {
        eventType: "stream-start";
    }

    export interface SearchQueriesGeneration extends Cohere.ChatSearchQueriesGenerationEvent {
        eventType: "search-queries-generation";
    }

    export interface SearchResults extends Cohere.ChatSearchResultsEvent {
        eventType: "search-results";
    }

    export interface TextGeneration extends Cohere.ChatTextGenerationEvent {
        eventType: "text-generation";
    }

    export interface CitationGeneration extends Cohere.ChatCitationGenerationEvent {
        eventType: "citation-generation";
    }

    export interface ToolCallsGeneration extends Cohere.ChatToolCallsGenerationEvent {
        eventType: "tool-calls-generation";
    }

    export interface StreamEnd extends Cohere.ChatStreamEndEvent {
        eventType: "stream-end";
    }

    export interface ToolCallsChunk extends Cohere.ChatToolCallsChunkEvent {
        eventType: "tool-calls-chunk";
    }

    export interface Debug extends Cohere.ChatDebugEvent {
        eventType: "debug";
    }
}
