/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cohere from "..";

export type StreamedGenerationItem = Cohere.GenerationStream | Cohere.GenerationFinalResponse;
