/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SummarizeResponseResultsItem {
    /** Generated ID for the summary */
    id?: string;
    /** Generated summary for the text */
    summary?: string;
}
