/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The identifier of the model to generate the summary with. Currently available models are `command` (default), `command-nightly` (experimental), `command-light`, and `command-light-nightly` (experimental). Smaller, "light" models are faster, while larger models will perform better.
 */
export type SummarizeRequestModel = "command" | "command-light";

export const SummarizeRequestModel = {
    Command: "command",
    CommandLight: "command-light",
} as const;
