/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         texts: []
 *     }
 */
export interface DetectLanguageRequest {
    /** List of strings to run the detection on. */
    texts: string[];
    /** The identifier of the model to generate with. */
    model?: string;
}
