/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cohere from "../..";

export interface UpdateClusterJobRequest {
    jobId?: string;
    status?: Cohere.UpdateClusterJobRequestStatus;
    clusters?: Cohere.Cluster[];
    outputClustersGsPath?: string;
    outputOutliersGsPath?: string;
    error?: string;
    inputTrackingMetrics?: Record<string, unknown>;
    outputTrackingMetrics?: Record<string, unknown>;
}
