/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cohere from "../../../../api/index";
import * as core from "../../../../core";
import { AssistantMessageContentItem } from "./AssistantMessageContentItem";

export const AssistantMessageContent: core.serialization.Schema<
    serializers.AssistantMessageContent.Raw,
    Cohere.AssistantMessageContent
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.list(AssistantMessageContentItem),
]);

export declare namespace AssistantMessageContent {
    type Raw = string | AssistantMessageContentItem.Raw[];
}
