/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cohere from "../../../../api/index";
import * as core from "../../../../core";
import { ChatToolCallDeltaEventDeltaToolCall } from "./ChatToolCallDeltaEventDeltaToolCall";

export const ChatToolCallDeltaEventDelta: core.serialization.ObjectSchema<
    serializers.ChatToolCallDeltaEventDelta.Raw,
    Cohere.ChatToolCallDeltaEventDelta
> = core.serialization.object({
    toolCall: core.serialization.property("tool_call", ChatToolCallDeltaEventDeltaToolCall.optional()),
});

export declare namespace ChatToolCallDeltaEventDelta {
    interface Raw {
        tool_call?: ChatToolCallDeltaEventDeltaToolCall.Raw | null;
    }
}
