/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cohere from "../../../../api/index";
import * as core from "../../../../core";

export const DocumentContentDocument: core.serialization.Schema<
    serializers.DocumentContentDocument.Raw,
    Cohere.DocumentContentDocument
> = core.serialization.undiscriminatedUnion([
    core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    core.serialization.string(),
]);

export declare namespace DocumentContentDocument {
    type Raw = Record<string, unknown> | string;
}
