/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cohere from "../../../../api/index";
import * as core from "../../../../core";

export const TextsTruncate: core.serialization.Schema<serializers.TextsTruncate.Raw, Cohere.TextsTruncate> =
    core.serialization.enum_(["NONE", "START", "END"]);

export declare namespace TextsTruncate {
    type Raw = "NONE" | "START" | "END";
}
