/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cohere from "../../../../api/index";
import * as core from "../../../../core";

export const ToolSource: core.serialization.ObjectSchema<serializers.ToolSource.Raw, Cohere.ToolSource> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        toolOutput: core.serialization.property(
            "tool_output",
            core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional()
        ),
    });

export declare namespace ToolSource {
    interface Raw {
        id?: string | null;
        tool_output?: Record<string, unknown> | null;
    }
}
