/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Cohere from "../../../../api/index";
import * as core from "../../../../core";
import { Document } from "./Document";

export const V2ChatStreamRequestDocumentsItem: core.serialization.Schema<
    serializers.V2ChatStreamRequestDocumentsItem.Raw,
    Cohere.V2ChatStreamRequestDocumentsItem
> = core.serialization.undiscriminatedUnion([core.serialization.string(), Document]);

export declare namespace V2ChatStreamRequestDocumentsItem {
    type Raw = string | Document.Raw;
}
