/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The reason a chat request has finished.
 */
export type ChatFinishReason =
    | "complete"
    | "stop_sequence"
    | "max_tokens"
    | "tool_call"
    | "error"
    | "content_blocked"
    | "error_limit";

export const ChatFinishReason = {
    Complete: "complete",
    StopSequence: "stop_sequence",
    MaxTokens: "max_tokens",
    ToolCall: "tool_call",
    Error: "error",
    ContentBlocked: "content_blocked",
    ErrorLimit: "error_limit",
} as const;
