/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Cohere from "../../../index";

/**
 * Citation information containing sources and the text cited.
 */
export interface Citation {
    start?: string;
    end?: string;
    text?: string;
    sources?: Cohere.Source[];
}
