/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Relevant information that could be used by the model to generate a more accurate reply.
 * The contents of each document are generally short (under 300 words), and are passed in the form of a
 * dictionary of strings or a single string. If a single string is passed, it will be treated as the value for key "content".
 */
export type DocumentContentDocument = Record<string, unknown> | string;
