/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A message from the system.
 */
export interface ToolMessage2 {
    /** The id of the associated tool call that has provided the given content */
    toolCallId: string;
    /** A list of outputs from a tool. The content should formatted as a JSON object string */
    toolContent: string[];
}
