/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Defaults to `"accurate"`.
 * Dictates the approach taken to generating citations as part of the RAG flow by allowing the user to specify whether they want `"accurate"` results, `"fast"` results or no results.
 */
export type V2ChatRequestCitationMode = "FAST" | "ACCURATE" | "OFF";

export const V2ChatRequestCitationMode = {
    Fast: "FAST",
    Accurate: "ACCURATE",
    Off: "OFF",
} as const;
