/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Cohere from "../../api/index";
import * as core from "../../core";
import { TextContent } from "./TextContent";

export const AssistantMessageContentItem: core.serialization.Schema<
    serializers.AssistantMessageContentItem.Raw,
    Cohere.AssistantMessageContentItem
> = core.serialization
    .union("type", {
        text: TextContent,
    })
    .transform<Cohere.AssistantMessageContentItem>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace AssistantMessageContentItem {
    type Raw = AssistantMessageContentItem.Text;

    interface Text extends TextContent.Raw {
        type: "text";
    }
}
