// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { ChatTextContent } from "./ChatTextContent";
import { ChatThinkingContent } from "./ChatThinkingContent";

export const AssistantMessageV2ContentItem: core.serialization.Schema<
    serializers.AssistantMessageV2ContentItem.Raw,
    Cohere.AssistantMessageV2ContentItem
> = core.serialization
    .union("type", {
        text: ChatTextContent,
        thinking: ChatThinkingContent,
    })
    .transform<Cohere.AssistantMessageV2ContentItem>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace AssistantMessageV2ContentItem {
    export type Raw = AssistantMessageV2ContentItem.Text | AssistantMessageV2ContentItem.Thinking;

    export interface Text extends ChatTextContent.Raw {
        type: "text";
    }

    export interface Thinking extends ChatThinkingContent.Raw {
        type: "thinking";
    }
}
