// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { AssistantMessageV2Content } from "./AssistantMessageV2Content";
import { Citation } from "./Citation";
import { ToolCallV2 } from "./ToolCallV2";

export const AssistantMessage: core.serialization.ObjectSchema<
    serializers.AssistantMessage.Raw,
    Cohere.AssistantMessage
> = core.serialization.object({
    toolCalls: core.serialization.property("tool_calls", core.serialization.list(ToolCallV2).optional()),
    toolPlan: core.serialization.property("tool_plan", core.serialization.string().optional()),
    content: AssistantMessageV2Content.optional(),
    citations: core.serialization.list(Citation).optional(),
});

export declare namespace AssistantMessage {
    export interface Raw {
        tool_calls?: ToolCallV2.Raw[] | null;
        tool_plan?: string | null;
        content?: AssistantMessageV2Content.Raw | null;
        citations?: Citation.Raw[] | null;
    }
}
