// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const AuthTokenType: core.serialization.Schema<serializers.AuthTokenType.Raw, Cohere.AuthTokenType> =
    core.serialization.enum_(["bearer", "basic", "noscheme"]);

export declare namespace AuthTokenType {
    export type Raw = "bearer" | "basic" | "noscheme";
}
