// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { ToolResult } from "./ToolResult";

export const ChatToolMessage: core.serialization.ObjectSchema<serializers.ChatToolMessage.Raw, Cohere.ChatToolMessage> =
    core.serialization.object({
        toolResults: core.serialization.property("tool_results", core.serialization.list(ToolResult).optional()),
    });

export declare namespace ChatToolMessage {
    export interface Raw {
        tool_results?: ToolResult.Raw[] | null;
    }
}
