/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Cohere from "../../api";
import * as core from "../../core";

export const ChatStreamStartEvent: core.serialization.ObjectSchema<
    serializers.ChatStreamStartEvent.Raw,
    Cohere.ChatStreamStartEvent
> = core.serialization
    .object({
        generationId: core.serialization.property("generation_id", core.serialization.string()),
    })
    .extend(core.serialization.lazyObject(async () => (await import("..")).ChatStreamEvent));

export declare namespace ChatStreamStartEvent {
    interface Raw extends serializers.ChatStreamEvent.Raw {
        generation_id: string;
    }
}
