// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const ChatToolPlanDeltaEventDeltaMessage: core.serialization.ObjectSchema<
    serializers.ChatToolPlanDeltaEventDeltaMessage.Raw,
    Cohere.ChatToolPlanDeltaEventDeltaMessage
> = core.serialization.object({
    toolPlan: core.serialization.property("tool_plan", core.serialization.string().optional()),
});

export declare namespace ChatToolPlanDeltaEventDeltaMessage {
    export interface Raw {
        tool_plan?: string | null;
    }
}
