/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Cohere from "../../api";
import * as core from "../../core";

export const ChatToolCallsGenerationEvent: core.serialization.ObjectSchema<
    serializers.ChatToolCallsGenerationEvent.Raw,
    Cohere.ChatToolCallsGenerationEvent
> = core.serialization
    .object({
        toolCalls: core.serialization.property(
            "tool_calls",
            core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).ToolCall))
        ),
    })
    .extend(core.serialization.lazyObject(async () => (await import("..")).ChatStreamEvent));

export declare namespace ChatToolCallsGenerationEvent {
    interface Raw extends serializers.ChatStreamEvent.Raw {
        tool_calls: serializers.ToolCall.Raw[];
    }
}
