/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Cohere from "../../api";
import * as core from "../../core";

export const ChatSearchResultConnector: core.serialization.ObjectSchema<
    serializers.ChatSearchResultConnector.Raw,
    Cohere.ChatSearchResultConnector
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace ChatSearchResultConnector {
    interface Raw {
        id: string;
    }
}
