/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Cohere from "../../api/index";
import * as core from "../../core";
import { ChatStreamEndEventFinishReason } from "./ChatStreamEndEventFinishReason";
import { NonStreamedChatResponse } from "./NonStreamedChatResponse";
import { ChatStreamEvent } from "./ChatStreamEvent";

export const ChatStreamEndEvent: core.serialization.ObjectSchema<
    serializers.ChatStreamEndEvent.Raw,
    Cohere.ChatStreamEndEvent
> = core.serialization
    .object({
        finishReason: core.serialization.property("finish_reason", ChatStreamEndEventFinishReason),
        response: NonStreamedChatResponse,
    })
    .extend(ChatStreamEvent);

export declare namespace ChatStreamEndEvent {
    export interface Raw extends ChatStreamEvent.Raw {
        finish_reason: ChatStreamEndEventFinishReason.Raw;
        response: NonStreamedChatResponse.Raw;
    }
}
