// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { ChatMessageV2 } from "./ChatMessageV2";

export const ChatMessages: core.serialization.Schema<serializers.ChatMessages.Raw, Cohere.ChatMessages> =
    core.serialization.list(ChatMessageV2);

export declare namespace ChatMessages {
    export type Raw = ChatMessageV2.Raw[];
}
