/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Cohere from "../../api/index";
import * as core from "../../core";

export const ChatRequestResponseFormatType: core.serialization.Schema<
    serializers.ChatRequestResponseFormatType.Raw,
    Cohere.ChatRequestResponseFormatType
> = core.serialization.enum_(["text", "json_object"]);

export declare namespace ChatRequestResponseFormatType {
    type Raw = "text" | "json_object";
}
