// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const ChatStreamRequestCitationQuality: core.serialization.Schema<
    serializers.ChatStreamRequestCitationQuality.Raw,
    Cohere.ChatStreamRequestCitationQuality
> = core.serialization.enum_(["ENABLED", "DISABLED", "FAST", "ACCURATE", "OFF"]);

export declare namespace ChatStreamRequestCitationQuality {
    export type Raw = "ENABLED" | "DISABLED" | "FAST" | "ACCURATE" | "OFF";
}
