/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Cohere from "../../api/index";
import * as core from "../../core";
import { ChatStreamEvent } from "./ChatStreamEvent";

export const ChatDebugEvent: core.serialization.ObjectSchema<serializers.ChatDebugEvent.Raw, Cohere.ChatDebugEvent> =
    core.serialization
        .object({
            prompt: core.serialization.string().optional(),
        })
        .extend(ChatStreamEvent);

export declare namespace ChatDebugEvent {
    export interface Raw extends ChatStreamEvent.Raw {
        prompt?: string | null;
    }
}
