/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Cohere from "../../api";
import * as core from "../../core";

export const ChatRequestToolResultsItem: core.serialization.ObjectSchema<
    serializers.ChatRequestToolResultsItem.Raw,
    Cohere.ChatRequestToolResultsItem
> = core.serialization.object({
    call: core.serialization.lazyObject(async () => (await import("..")).ToolCall),
    outputs: core.serialization.list(
        core.serialization.record(core.serialization.string(), core.serialization.unknown())
    ),
});

export declare namespace ChatRequestToolResultsItem {
    interface Raw {
        call: serializers.ToolCall.Raw;
        outputs: Record<string, unknown>[];
    }
}
