// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { ChatToolCallDeltaEventDeltaMessageToolCalls } from "./ChatToolCallDeltaEventDeltaMessageToolCalls";

export const ChatToolCallDeltaEventDeltaMessage: core.serialization.ObjectSchema<
    serializers.ChatToolCallDeltaEventDeltaMessage.Raw,
    Cohere.ChatToolCallDeltaEventDeltaMessage
> = core.serialization.object({
    toolCalls: core.serialization.property("tool_calls", ChatToolCallDeltaEventDeltaMessageToolCalls.optional()),
});

export declare namespace ChatToolCallDeltaEventDeltaMessage {
    export interface Raw {
        tool_calls?: ChatToolCallDeltaEventDeltaMessageToolCalls.Raw | null;
    }
}
