/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Cohere from "../../api/index";
import * as core from "../../core";
import { ChatToolCallStartEventDelta } from "./ChatToolCallStartEventDelta";
import { ChatStreamEventType } from "./ChatStreamEventType";

export const ChatToolCallStartEvent: core.serialization.ObjectSchema<
    serializers.ChatToolCallStartEvent.Raw,
    Cohere.ChatToolCallStartEvent
> = core.serialization
    .object({
        index: core.serialization.number().optional(),
        delta: ChatToolCallStartEventDelta.optional(),
    })
    .extend(ChatStreamEventType);

export declare namespace ChatToolCallStartEvent {
    export interface Raw extends ChatStreamEventType.Raw {
        index?: number | null;
        delta?: ChatToolCallStartEventDelta.Raw | null;
    }
}
