// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const ChatDocument: core.serialization.Schema<serializers.ChatDocument.Raw, Cohere.ChatDocument> =
    core.serialization.record(core.serialization.string(), core.serialization.string());

export declare namespace ChatDocument {
    export type Raw = Record<string, string>;
}
