/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Cohere from "../../api/index";
import * as core from "../../core";

export const ChatContentStartEventDeltaMessageContentType: core.serialization.Schema<
    serializers.ChatContentStartEventDeltaMessageContentType.Raw,
    Cohere.ChatContentStartEventDeltaMessageContentType
> = core.serialization.enum_(["text", "thinking"]);

export declare namespace ChatContentStartEventDeltaMessageContentType {
    export type Raw = "text" | "thinking";
}
