// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const ChatContentDeltaEventDeltaMessageContent: core.serialization.ObjectSchema<
    serializers.ChatContentDeltaEventDeltaMessageContent.Raw,
    Cohere.ChatContentDeltaEventDeltaMessageContent
> = core.serialization.object({
    thinking: core.serialization.string().optional(),
    text: core.serialization.string().optional(),
});

export declare namespace ChatContentDeltaEventDeltaMessageContent {
    export interface Raw {
        thinking?: string | null;
        text?: string | null;
    }
}
