// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const CheckApiKeyResponse: core.serialization.ObjectSchema<
    serializers.CheckApiKeyResponse.Raw,
    Cohere.CheckApiKeyResponse
> = core.serialization.object({
    valid: core.serialization.boolean(),
    organizationId: core.serialization.property("organization_id", core.serialization.string().optional()),
    ownerId: core.serialization.property("owner_id", core.serialization.string().optional()),
});

export declare namespace CheckApiKeyResponse {
    export interface Raw {
        valid: boolean;
        organization_id?: string | null;
        owner_id?: string | null;
    }
}
