// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { CitationOptionsMode } from "./CitationOptionsMode";

export const CitationOptions: core.serialization.ObjectSchema<serializers.CitationOptions.Raw, Cohere.CitationOptions> =
    core.serialization.object({
        mode: CitationOptionsMode.optional(),
    });

export declare namespace CitationOptions {
    export interface Raw {
        mode?: CitationOptionsMode.Raw | null;
    }
}
