/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Cohere from "../../api";
import * as core from "../../core";

export const ClassifyRequestExamplesItem: core.serialization.ObjectSchema<
    serializers.ClassifyRequestExamplesItem.Raw,
    Cohere.ClassifyRequestExamplesItem
> = core.serialization.object({
    text: core.serialization.string().optional(),
    label: core.serialization.string().optional(),
});

export declare namespace ClassifyRequestExamplesItem {
    interface Raw {
        text?: string | null;
        label?: string | null;
    }
}
