// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const ClassifyResponseClassificationsItemClassificationType: core.serialization.Schema<
    serializers.ClassifyResponseClassificationsItemClassificationType.Raw,
    Cohere.ClassifyResponseClassificationsItemClassificationType
> = core.serialization.enum_(["single-label", "multi-label"]);

export declare namespace ClassifyResponseClassificationsItemClassificationType {
    export type Raw = "single-label" | "multi-label";
}
