/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Cohere from "../../api";
import * as core from "../../core";

export const Connector: core.serialization.ObjectSchema<serializers.Connector.Raw, Cohere.Connector> =
    core.serialization.object({
        id: core.serialization.string(),
        organizationId: core.serialization.string().optional(),
        name: core.serialization.string(),
        description: core.serialization.string().optional(),
        url: core.serialization.string().optional(),
        createdAt: core.serialization.date(),
        updatedAt: core.serialization.date(),
        excludes: core.serialization.list(core.serialization.string()).optional(),
        authType: core.serialization.string().optional(),
        oauth: core.serialization.lazyObject(async () => (await import("..")).ConnectorOAuth).optional(),
        authStatus: core.serialization.lazy(async () => (await import("..")).ConnectorAuthStatus).optional(),
        active: core.serialization.boolean().optional(),
        continueOnFailure: core.serialization.boolean().optional(),
    });

export declare namespace Connector {
    interface Raw {
        id: string;
        organizationId?: string | null;
        name: string;
        description?: string | null;
        url?: string | null;
        createdAt: string;
        updatedAt: string;
        excludes?: string[] | null;
        authType?: string | null;
        oauth?: serializers.ConnectorOAuth.Raw | null;
        authStatus?: serializers.ConnectorAuthStatus.Raw | null;
        active?: boolean | null;
        continueOnFailure?: boolean | null;
    }
}
