/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Cohere from "../../api";
import * as core from "../../core";

export const CreateEmbedJobResponse: core.serialization.ObjectSchema<
    serializers.CreateEmbedJobResponse.Raw,
    Cohere.CreateEmbedJobResponse
> = core.serialization.object({
    jobId: core.serialization.property("job_id", core.serialization.string()),
    meta: core.serialization.lazyObject(async () => (await import("..")).ApiMeta).optional(),
});

export declare namespace CreateEmbedJobResponse {
    interface Raw {
        job_id: string;
        meta?: serializers.ApiMeta.Raw | null;
    }
}
