// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const DeleteConnectorResponse: core.serialization.Schema<
    serializers.DeleteConnectorResponse.Raw,
    Cohere.DeleteConnectorResponse
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace DeleteConnectorResponse {
    export type Raw = Record<string, unknown>;
}
