/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Cohere from "../../api";
import * as core from "../../core";

export const DetectLanguageResponse: core.serialization.ObjectSchema<
    serializers.DetectLanguageResponse.Raw,
    Cohere.DetectLanguageResponse
> = core.serialization.object({
    results: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("..")).DetectLanguageResponseResultsItem))
        .optional(),
    meta: core.serialization.lazyObject(async () => (await import("..")).ApiMeta).optional(),
});

export declare namespace DetectLanguageResponse {
    interface Raw {
        results?: serializers.DetectLanguageResponseResultsItem.Raw[] | null;
        meta?: serializers.ApiMeta.Raw | null;
    }
}
