// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { ApiMeta } from "./ApiMeta";

export const DetokenizeResponse: core.serialization.ObjectSchema<
    serializers.DetokenizeResponse.Raw,
    Cohere.DetokenizeResponse
> = core.serialization.object({
    text: core.serialization.string(),
    meta: ApiMeta.optional(),
});

export declare namespace DetokenizeResponse {
    export interface Raw {
        text: string;
        meta?: ApiMeta.Raw | null;
    }
}
