/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Cohere from "../../api/index";
import * as core from "../../core";
import { EmbedContent } from "./EmbedContent";

export const EmbedInput: core.serialization.ObjectSchema<serializers.EmbedInput.Raw, Cohere.EmbedInput> =
    core.serialization.object({
        content: core.serialization.list(EmbedContent),
    });

export declare namespace EmbedInput {
    export interface Raw {
        content: EmbedContent.Raw[];
    }
}
