/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Cohere from "../../api";
import * as core from "../../core";

export const EmbedRequestEmbeddingTypesItem: core.serialization.Schema<
    serializers.EmbedRequestEmbeddingTypesItem.Raw,
    Cohere.EmbedRequestEmbeddingTypesItem
> = core.serialization.enum_(["float", "int8", "uint8", "binary", "ubinary"]);

export declare namespace EmbedRequestEmbeddingTypesItem {
    type Raw = "float" | "int8" | "uint8" | "binary" | "ubinary";
}
