/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Cohere from "../../api";
import * as core from "../../core";

export const EmbedFloatsResponse: core.serialization.ObjectSchema<
    serializers.EmbedFloatsResponse.Raw,
    Cohere.EmbedFloatsResponse
> = core.serialization.object({
    id: core.serialization.string(),
    embeddings: core.serialization.list(core.serialization.list(core.serialization.number())),
    texts: core.serialization.list(core.serialization.string()),
    meta: core.serialization.lazyObject(async () => (await import("..")).ApiMeta).optional(),
});

export declare namespace EmbedFloatsResponse {
    interface Raw {
        id: string;
        embeddings: number[][];
        texts: string[];
        meta?: serializers.ApiMeta.Raw | null;
    }
}
