// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { EmbedByTypeResponse } from "./EmbedByTypeResponse";
import { EmbedFloatsResponse } from "./EmbedFloatsResponse";

export const EmbedResponse: core.serialization.Schema<serializers.EmbedResponse.Raw, Cohere.EmbedResponse> =
    core.serialization
        .union(core.serialization.discriminant("responseType", "response_type"), {
            embeddings_floats: EmbedFloatsResponse,
            embeddings_by_type: EmbedByTypeResponse,
        })
        .transform<Cohere.EmbedResponse>({
            transform: (value) => value,
            untransform: (value) => value,
        });

export declare namespace EmbedResponse {
    export type Raw = EmbedResponse.EmbeddingsFloats | EmbedResponse.EmbeddingsByType;

    export interface EmbeddingsFloats extends EmbedFloatsResponse.Raw {
        response_type: "embeddings_floats";
    }

    export interface EmbeddingsByType extends EmbedByTypeResponse.Raw {
        response_type: "embeddings_by_type";
    }
}
