// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const EmbedByTypeResponseResponseType: core.serialization.Schema<
    serializers.EmbedByTypeResponseResponseType.Raw,
    Cohere.EmbedByTypeResponseResponseType
> = core.serialization.enum_(["embeddings_floats", "embeddings_by_type"]);

export declare namespace EmbedByTypeResponseResponseType {
    export type Raw = "embeddings_floats" | "embeddings_by_type";
}
