/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Cohere from "../../api/index";
import * as core from "../../core";
import { EmbedImageProperties } from "./EmbedImageProperties";

export const EmbedImage: core.serialization.ObjectSchema<serializers.EmbedImage.Raw, Cohere.EmbedImage> =
    core.serialization.object({
        image: EmbedImageProperties.optional(),
    });

export declare namespace EmbedImage {
    interface Raw {
        image?: EmbedImageProperties.Raw | null;
    }
}
