/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Cohere from "../../api/index";
import * as core from "../../core";

export const GatewayTimeoutErrorBody: core.serialization.ObjectSchema<
    serializers.GatewayTimeoutErrorBody.Raw,
    Cohere.GatewayTimeoutErrorBody
> = core.serialization.object({
    data: core.serialization.string().optional(),
});

export declare namespace GatewayTimeoutErrorBody {
    interface Raw {
        data?: string | null;
    }
}
