/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Cohere from "../../api";
import * as core from "../../core";

export const Generation: core.serialization.ObjectSchema<serializers.Generation.Raw, Cohere.Generation> =
    core.serialization.object({
        id: core.serialization.string(),
        prompt: core.serialization.string().optional(),
        generations: core.serialization.list(
            core.serialization.lazyObject(async () => (await import("..")).SingleGeneration)
        ),
        meta: core.serialization.lazyObject(async () => (await import("..")).ApiMeta).optional(),
    });

export declare namespace Generation {
    interface Raw {
        id: string;
        prompt?: string | null;
        generations: serializers.SingleGeneration.Raw[];
        meta?: serializers.ApiMeta.Raw | null;
    }
}
