// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { ApiMeta } from "./ApiMeta";
import { SingleGeneration } from "./SingleGeneration";

export const Generation: core.serialization.ObjectSchema<serializers.Generation.Raw, Cohere.Generation> =
    core.serialization.object({
        id: core.serialization.string(),
        prompt: core.serialization.string().optional(),
        generations: core.serialization.list(SingleGeneration),
        meta: ApiMeta.optional(),
    });

export declare namespace Generation {
    export interface Raw {
        id: string;
        prompt?: string | null;
        generations: SingleGeneration.Raw[];
        meta?: ApiMeta.Raw | null;
    }
}
