/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Cohere from "../../api";
import * as core from "../../core";
import { Connector } from "./Connector";

export const GetConnectorResponse: core.serialization.ObjectSchema<
    serializers.GetConnectorResponse.Raw,
    Cohere.GetConnectorResponse
> = core.serialization.object({
    connector: Connector,
});

export declare namespace GetConnectorResponse {
    interface Raw {
        connector: Connector.Raw;
    }
}
