/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Cohere from "../../api";
import * as core from "../../core";

export const GetClusterJobResponseStatus: core.serialization.Schema<
    serializers.GetClusterJobResponseStatus.Raw,
    Cohere.GetClusterJobResponseStatus
> = core.serialization.enum_(["unknown", "processing", "failed", "complete", "queued"]);

export declare namespace GetClusterJobResponseStatus {
    type Raw = "unknown" | "processing" | "failed" | "complete" | "queued";
}
