// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { ImageUrlDetail } from "./ImageUrlDetail";

export const ImageUrl: core.serialization.ObjectSchema<serializers.ImageUrl.Raw, Cohere.ImageUrl> =
    core.serialization.object({
        url: core.serialization.string(),
        detail: ImageUrlDetail.optional(),
    });

export declare namespace ImageUrl {
    export interface Raw {
        url: string;
        detail?: ImageUrlDetail.Raw | null;
    }
}
