/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Cohere from "../../api/index";
import * as core from "../../core";

export const Image: core.serialization.ObjectSchema<serializers.Image.Raw, Cohere.Image> = core.serialization.object({
    width: core.serialization.number(),
    height: core.serialization.number(),
    format: core.serialization.string(),
    bitDepth: core.serialization.property("bit_depth", core.serialization.number()),
});

export declare namespace Image {
    export interface Raw {
        width: number;
        height: number;
        format: string;
        bit_depth: number;
    }
}
