/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Cohere from "../../api/index";
import * as core from "../../core";

export const JsonResponseFormat: core.serialization.ObjectSchema<
    serializers.JsonResponseFormat.Raw,
    Cohere.JsonResponseFormat
> = core.serialization.object({
    schema: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace JsonResponseFormat {
    export interface Raw {
        schema?: Record<string, unknown> | null;
    }
}
