// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { GetModelResponse } from "./GetModelResponse";

export const ListModelsResponse: core.serialization.ObjectSchema<
    serializers.ListModelsResponse.Raw,
    Cohere.ListModelsResponse
> = core.serialization.object({
    models: core.serialization.list(GetModelResponse),
    nextPageToken: core.serialization.property("next_page_token", core.serialization.string().optional()),
});

export declare namespace ListModelsResponse {
    export interface Raw {
        models: GetModelResponse.Raw[];
        next_page_token?: string | null;
    }
}
