/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Cohere from "../../api";
import * as core from "../../core";

export const ListEmbedJobResponse: core.serialization.ObjectSchema<
    serializers.ListEmbedJobResponse.Raw,
    Cohere.ListEmbedJobResponse
> = core.serialization.object({
    embedJobs: core.serialization.property(
        "embed_jobs",
        core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).EmbedJob)).optional()
    ),
});

export declare namespace ListEmbedJobResponse {
    interface Raw {
        embed_jobs?: serializers.EmbedJob.Raw[] | null;
    }
}
