/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Cohere from "../../api";
import * as core from "../../core";

export const NonStreamedChatResponse: core.serialization.ObjectSchema<
    serializers.NonStreamedChatResponse.Raw,
    Cohere.NonStreamedChatResponse
> = core.serialization.object({
    text: core.serialization.string(),
    generationId: core.serialization.property("generation_id", core.serialization.string()),
    citations: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("..")).ChatCitation))
        .optional(),
    documents: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("..")).ChatDocument))
        .optional(),
    searchQueries: core.serialization.property(
        "search_queries",
        core.serialization
            .list(core.serialization.lazyObject(async () => (await import("..")).ChatSearchQuery))
            .optional()
    ),
    searchResults: core.serialization.property(
        "search_results",
        core.serialization
            .list(core.serialization.lazyObject(async () => (await import("..")).ChatSearchResult))
            .optional()
    ),
});

export declare namespace NonStreamedChatResponse {
    interface Raw {
        text: string;
        generation_id: string;
        citations?: serializers.ChatCitation.Raw[] | null;
        documents?: serializers.ChatDocument.Raw[] | null;
        search_queries?: serializers.ChatSearchQuery.Raw[] | null;
        search_results?: serializers.ChatSearchResult.Raw[] | null;
    }
}
