// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { ParseMarkdownPage } from "./ParseMarkdownPage";

export const ParseMarkdownPageVariant: core.serialization.ObjectSchema<
    serializers.ParseMarkdownPageVariant.Raw,
    Cohere.ParseMarkdownPageVariant
> = core.serialization.object({
    index: core.serialization.number(),
    markdown: ParseMarkdownPage,
});

export declare namespace ParseMarkdownPageVariant {
    export interface Raw {
        index: number;
        markdown: ParseMarkdownPage.Raw;
    }
}
