// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const ParseBoundingBox: core.serialization.ObjectSchema<
    serializers.ParseBoundingBox.Raw,
    Cohere.ParseBoundingBox
> = core.serialization.object({
    topLeftX: core.serialization.property("top_left_x", core.serialization.number()),
    topLeftY: core.serialization.property("top_left_y", core.serialization.number()),
    bottomRightX: core.serialization.property("bottom_right_x", core.serialization.number()),
    bottomRightY: core.serialization.property("bottom_right_y", core.serialization.number()),
});

export declare namespace ParseBoundingBox {
    export interface Raw {
        top_left_x: number;
        top_left_y: number;
        bottom_right_x: number;
        bottom_right_y: number;
    }
}
