/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Cohere from "../../api/index";
import * as core from "../../core";

export const ReasoningEffort: core.serialization.Schema<serializers.ReasoningEffort.Raw, Cohere.ReasoningEffort> =
    core.serialization.enum_(["low", "medium", "high"]);

export declare namespace ReasoningEffort {
    type Raw = "low" | "medium" | "high";
}
