/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Cohere from "../../api";
import * as core from "../../core";
import { RerankRequestDocumentsItemText } from "./RerankRequestDocumentsItemText";

export const RerankRequestDocumentsItem: core.serialization.Schema<
    serializers.RerankRequestDocumentsItem.Raw,
    Cohere.RerankRequestDocumentsItem
> = core.serialization.undiscriminatedUnion([core.serialization.string(), RerankRequestDocumentsItemText]);

export declare namespace RerankRequestDocumentsItem {
    type Raw = string | RerankRequestDocumentsItemText.Raw;
}
