/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Cohere from "../../api/index";
import * as core from "../../core";
import { SingleGenerationTokenLikelihoodsItem } from "./SingleGenerationTokenLikelihoodsItem";

export const SingleGeneration: core.serialization.ObjectSchema<
    serializers.SingleGeneration.Raw,
    Cohere.SingleGeneration
> = core.serialization.object({
    id: core.serialization.string(),
    text: core.serialization.string(),
    index: core.serialization.number().optional(),
    likelihood: core.serialization.number().optional(),
    tokenLikelihoods: core.serialization.property(
        "token_likelihoods",
        core.serialization.list(SingleGenerationTokenLikelihoodsItem).optional(),
    ),
});

export declare namespace SingleGeneration {
    export interface Raw {
        id: string;
        text: string;
        index?: number | null;
        likelihood?: number | null;
        token_likelihoods?: SingleGenerationTokenLikelihoodsItem.Raw[] | null;
    }
}
