/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Cohere from "../../api/index";
import * as core from "../../core";
import { ChatTextContent } from "./ChatTextContent";

export const SystemMessageV2ContentItem: core.serialization.Schema<
    serializers.SystemMessageV2ContentItem.Raw,
    Cohere.SystemMessageV2ContentItem
> = core.serialization
    .union("type", {
        text: ChatTextContent,
    })
    .transform<Cohere.SystemMessageV2ContentItem>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace SystemMessageV2ContentItem {
    export type Raw = SystemMessageV2ContentItem.Text;

    export interface Text extends ChatTextContent.Raw {
        type: "text";
    }
}
