/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Cohere from "../../api";
import * as core from "../../core";

export const TokenizeResponse: core.serialization.ObjectSchema<
    serializers.TokenizeResponse.Raw,
    Cohere.TokenizeResponse
> = core.serialization.object({
    tokens: core.serialization.list(core.serialization.number()),
    tokenStrings: core.serialization.property("token_strings", core.serialization.list(core.serialization.string())),
    meta: core.serialization.lazyObject(async () => (await import("..")).ApiMeta).optional(),
});

export declare namespace TokenizeResponse {
    interface Raw {
        tokens: number[];
        token_strings: string[];
        meta?: serializers.ApiMeta.Raw | null;
    }
}
