/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Cohere from "../../api/index";
import * as core from "../../core";
import { ToolResult } from "./ToolResult";

export const ToolMessage: core.serialization.ObjectSchema<serializers.ToolMessage.Raw, Cohere.ToolMessage> =
    core.serialization.object({
        toolResults: core.serialization.property("tool_results", core.serialization.list(ToolResult).optional()),
    });

export declare namespace ToolMessage {
    interface Raw {
        tool_results?: ToolResult.Raw[] | null;
    }
}
