/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Cohere from "../../api/index";
import * as core from "../../core";

export const ToolParameterDefinitionsValue: core.serialization.ObjectSchema<
    serializers.ToolParameterDefinitionsValue.Raw,
    Cohere.ToolParameterDefinitionsValue
> = core.serialization.object({
    description: core.serialization.string().optional(),
    type: core.serialization.string(),
    required: core.serialization.boolean().optional(),
});

export declare namespace ToolParameterDefinitionsValue {
    interface Raw {
        description?: string | null;
        type: string;
        required?: boolean | null;
    }
}
