// This file was auto-generated by Fern from our API Definition.

import type * as Cohere from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { ToolContent } from "./ToolContent";

export const ToolMessageV2Content: core.serialization.Schema<
    serializers.ToolMessageV2Content.Raw,
    Cohere.ToolMessageV2Content
> = core.serialization.undiscriminatedUnion([core.serialization.string(), core.serialization.list(ToolContent)]);

export declare namespace ToolMessageV2Content {
    export type Raw = string | ToolContent.Raw[];
}
