/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Cohere from "../../api";
import * as core from "../../core";

export const UpdateConnectorResponse: core.serialization.ObjectSchema<
    serializers.UpdateConnectorResponse.Raw,
    Cohere.UpdateConnectorResponse
> = core.serialization.object({
    connector: core.serialization.lazyObject(async () => (await import("..")).Connector),
});

export declare namespace UpdateConnectorResponse {
    interface Raw {
        connector: serializers.Connector.Raw;
    }
}
