/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Cohere from "../../api/index";
import * as core from "../../core";

export const Usage: core.serialization.ObjectSchema<serializers.Usage.Raw, Cohere.Usage> = core.serialization.object({
    cachedTokens: core.serialization.property("cached_tokens", core.serialization.number().optional()),
});

export declare namespace Usage {
    export interface Raw {
        cached_tokens?: number | null;
    }
}
