/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 *
 * @example
 *     {
 *         pageSize: 1,
 *         pageToken: "string"
 *     }
 *
 * @example
 *     {
 *         pageSize: 1,
 *         pageToken: "string"
 *     }
 *
 * @example
 *     {
 *         pageSize: 1,
 *         pageToken: "string"
 *     }
 *
 * @example
 *     {
 *         pageSize: 1,
 *         pageToken: "string"
 *     }
 *
 * @example
 *     {
 *         pageSize: 1,
 *         pageToken: "string"
 *     }
 *
 * @example
 *     {
 *         pageSize: 1,
 *         pageToken: "string"
 *     }
 *
 * @example
 *     {
 *         pageSize: 1,
 *         pageToken: "string"
 *     }
 */
export interface FinetuningListTrainingStepMetricsRequest {
    /**
     * Maximum number of results to be returned by the server. If 0, defaults to 50.
     */
    pageSize?: number;
    /**
     * Request a specific page of the list results.
     */
    pageToken?: string;
}
